{% set name = "myst-nb-bokeh" %}
{% set version = "1.0.0.post3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/myst-nb-bokeh-{{ version }}.tar.gz
  sha256: 8a8af05ecc3b1e0a491cdced90e0565589ca54cd52d6ccaebe1ad130314d28aa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - pdm-pep517 >=1.0.0
  run:
    - bokeh >=3.0.0
    - ipython >=7.0
    - myst-nb >=0.17.1,<0.18
    - python >=3.9
    - sphinx >=4.5,<6
    - docutils # Add this to satisfy the linter, but let upstream dependencies pin the version

test:
  imports:
    - myst_nb_bokeh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bryanwweber/myst-nb-bokeh
  summary: MyST-NB-Bokeh includes functions for gluing and pasting Bokeh figures in MyST documents.
  dev_url: https://github.com/bryanwweber/myst-nb-bokeh
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
