{% set python_min = '3.10' %}
{% set name = "myst-nb-bokeh" %}
{% set version = "2024.1.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7e8ad0fc569c04d0714dc100864fc6fdd24c45f7f4ef87a262c8c8ff48bee4d5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend >=2.1.8
  run:
    - bokeh >=3.3.4
    - ipython >=8.20.0
    - myst-nb >=1.0.0
    - python >={{ python_min }}
    - sphinx >=7.2.6
    - docutils # Add this to satisfy the linter, but let upstream dependencies pin the version

test:
  imports:
    - myst_nb_bokeh
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bryanwweber/myst-nb-bokeh
  summary: MyST-NB-Bokeh includes functions for gluing and pasting Bokeh figures in MyST-NB documents.
  dev_url: https://github.com/bryanwweber/myst-nb-bokeh
  doc_url: https://myst-nb-bokeh.readthedocs.io
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bryanwweber
